# Generated by Django 5.0.4 on 2025-11-21 02:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jug_tag', models.CharField(blank=True, max_length=100)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('daily_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='pos_sales_date_5fa95a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(choices=[('admin', 'Administrator'), ('driver', 'Driver'), ('staff', 'General Staff'), ('manager', 'Manager')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_status', models.BooleanField(default=False)),
                ('jug_status', models.CharField(choices=[('picked_up', 'Picked Up'), ('transporting', 'Transporting'), ('delivered', 'Delivered'), ('refilling', 'Refilling')], default='picked_up', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pos.customer')),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'position': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.staff')),
            ],
            options={
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['order_date'], name='pos_order_order_d_60e5a9_idx'), models.Index(fields=['paid_status'], name='pos_order_paid_st_0ec9fc_idx'), models.Index(fields=['jug_status'], name='pos_order_jug_sta_deaab6_idx')],
            },
        ),
    ]
