# Generated by Django 5.0.4 on 2025-11-17 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0005_alter_customer_user_admin_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('transporting', 'Transporting'), ('delivered', 'Delivered'), ('picked_up', 'Picked_up')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pos.delivery')),
            ],
        ),
    ]
