# Generated by Django 5.0.4 on 2025-10-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('transporting', 'Transporting'), ('delivered', 'Delivered'), ('picked_up', 'Picked_up')], max_length=20),
        ),
    ]
