# Generated by Django 5.0.4 on 2025-11-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('pos', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pos.customer'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('transporting', 'Transporting'), ('delivered', 'Delivered'), ('picked_up', 'Picked_up')], max_length=20),
        ),
    ]
