# Generated by Django 5.0.4 on 2025-11-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_delivery_customer'),
        ('pos', '0006_remove_inventory_product_remove_payment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='pos.order'),
        ),
    ]
