<<<<<<< HEAD
# Generated by Django 5.0.4 on 2025-11-12 04:14
=======
# Generated by Django 5.2.4 on 2025-11-12 04:12
>>>>>>> 7cea9386eee562d60796ee007cf90287e079e7b8

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_delivery_status'),
        ('pos', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pos.customer'),
        ),
    ]
